# Generated by Django 2.1.7 on 2019-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190219_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locNumber', models.CharField(blank=True, choices=[('000-099', 'Generalities'), ('100-199', 'Philosophy'), ('200-299', 'Religion'), ('300-399', 'Social Science'), ('400-499', 'Language'), ('500-599', 'Science & Math'), ('600-699', 'Technology'), ('700-799', 'The Arts'), ('800-899', 'Literature'), ('900-999', 'Geography & History')], help_text='Book Location', max_length=7)),
            ],
        ),
    ]
