# Generated by Django 2.1.7 on 2019-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_locaton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locaton',
        ),
        migrations.AddField(
            model_name='book',
            name='locNumber',
            field=models.CharField(blank=True, choices=[('000-099', 'Generalities'), ('100-199', 'Philosophy'), ('200-299', 'Religion'), ('300-399', 'Social Science'), ('400-499', 'Language'), ('500-599', 'Science & Math'), ('600-699', 'Technology'), ('700-799', 'The Arts'), ('800-899', 'Literature'), ('900-999', 'Geography & History')], help_text='Book Location', max_length=7),
        ),
    ]
