# Generated by Django 2.1.7 on 2019-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190311_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('secretQuestion', models.IntegerField(choices=[(1, 'Whats the name of your first pet?'), (2, "Who's your childhood superhero?"), (3, "What is your mother's maiden name?"), (4, 'Who is your favorite teacher?')], default=1)),
                ('secretAnswer', models.CharField(max_length=100)),
            ],
        ),
    ]
