# Generated by Django 2.1.7 on 2019-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secretQuestion',
            field=models.IntegerField(choices=[(1, 'Whats the name of your first pet?'), (2, 'Who is your childhood superhero?'), (3, "What is your mother's maiden name?"), (4, 'Who is your favorite teacher?')], default=1),
        ),
    ]
