# Generated by Django 2.1.7 on 2019-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190312_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secretQuestion',
        ),
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=50),
        ),
    ]
