# Generated by Django 2.1.7 on 2019-03-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_profile_middle_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
