# Generated by Django 2.1.5 on 2019-03-14 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20190314_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominstance',
            name='room_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
