# Generated by Django 2.1.7 on 2019-03-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
